# Generated by Django 5.0.3 on 2024-08-19 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
                ('dept_descr', models.TextField(blank=True, null=True)),
                ('hod', models.CharField(blank=True, max_length=255, null=True)),
                ('hod_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hod_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('building_name', models.CharField(max_length=255)),
                ('room_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_code', models.CharField(max_length=50)),
                ('module_name', models.CharField(max_length=255)),
                ('module_type', models.CharField(blank=True, max_length=50, null=True)),
                ('module_year', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='timetablegen.department')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('program_year', models.IntegerField()),
                ('program_capacity', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='timetablegen.department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('rfid_id', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('staff_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_type', models.CharField(max_length=50)),
                ('staff_title', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='timetablegen.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('preference_weight', models.IntegerField(default=1)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='timetablegen.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('entry_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetablegen.module')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetablegen.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetablegen.staff')),
            ],
        ),
    ]
