# Generated by Django 5.1 on 2024-09-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetablegen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='department',
            new_name='dept_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='department',
            new_name='dept_id',
        ),
        migrations.RenameField(
            model_name='teacherpreference',
            old_name='staff',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='module',
            new_name='module_id',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='room',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='staff',
            new_name='staff_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='department',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_capacity',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_year',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='entry_year',
        ),
        migrations.AddField(
            model_name='module',
            name='nta_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='program_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='timetablegen.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='nta_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacherpreference',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_id', models.AutoField(primary_key=True, serialize=False)),
                ('Class_name', models.CharField(max_length=50)),
                ('class_capacity', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('class_stream', models.CharField(max_length=50)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='timetablegen.program')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='timetablegen.module')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='timetablegen.staff')),
            ],
            options={
                'unique_together': {('module_id', 'staff_id')},
            },
        ),
    ]
