# Generated by Django 5.1.3 on 2024-11-22 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetablegen', '0002_rename_department_program_dept_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('conflict_id', models.AutoField(primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('Room', 'Room'), ('Teacher', 'Teacher'), ('Class', 'Class')], max_length=10)),
                ('conflict_description', models.TextField(blank=True, null=True)),
                ('timetable_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_1', to='timetablegen.timetable')),
                ('timetable_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_2', to='timetablegen.timetable')),
            ],
            options={
                'verbose_name': 'Conflict',
                'verbose_name_plural': 'Conflicts',
                'db_table': 'conflicts',
            },
        ),
    ]
