# Generated by Django 5.1.3 on 2024-11-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetablegen', '0003_conflict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='program_id',
        ),
        migrations.AddField(
            model_name='module',
            name='module_credit',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ClassModuleAllocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_allocations', to='timetablegen.class')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='timetablegen.module')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='timetablegen.program')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_allocations', to='timetablegen.staff')),
            ],
            options={
                'verbose_name': 'Class Module Allocation',
                'verbose_name_plural': 'Class Module Allocations',
                'unique_together': {('class_id', 'module_id', 'staff_id')},
            },
        ),
        migrations.DeleteModel(
            name='ModuleAllocation',
        ),
    ]
