# Generated by Django 5.1.3 on 2024-11-24 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetablegen', '0004_remove_module_program_id_module_module_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetablegen.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_id', 'class_stream', 'day_of_week', 'start_time'), ('room_id', 'day_of_week', 'start_time'), ('staff_id', 'day_of_week', 'start_time')},
        ),
    ]
